name: '[DSP] Quality Engineering'

on:
  workflow_dispatch:
    inputs:
      cyRunnerBranch:
        description: 'Which branch to use on Cy-Runner?'
        default: 'main'
      cyRunnerTimeOut:
        description: 'Wait how much time (in minutes) for the job to complete?'
        default: '30'

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v2
    with:
      cypress: true
      cyRunnerBranch: ${{ inputs.cyRunnerBranch }}
      cyRunnerTimeOut: ${{ fromJSON(github.event.inputs.cyRunnerTimeOut) }}
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
