name: '[PRN] Quality Engineering'

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v2
    with:
      danger: true
      dangerRequireChangelog: false
      nodeLint: false
      nodeTest: false
      nodeSonar: false
      nodeSonarProjectKey: vtex-apps_checkout-ui-custom
      nodeSonarOrganization: vtex-apps
      cypress: false
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
